### PR TITLE
Users&Admins

### PR DESCRIPTION
**Pull request by Elkont33**

### CODE REVIEW

**Comment by amrdruid** [comment]
3daak el 3eeb :+1: 
bs don't you think if we used STI (Single table inherticance) will be better ? 
I mean if we added a column name `type` in user model, and any type of users after that (admins, doctors, patients ..) can inhert from this model, it'll be more efficient

**Comment by amrdruid** [comment]
To relate for both of us 
http://stackoverflow.com/questions/9472852/devise-and-multiple-user-models

**Comment by Elkont33** [comment]
I always had the problem of Super admins and normal admins so separating them completely was my solution, but we can discuss your method

**Comment by amrdruid** [comment]
Admin migration file still needs fix I think

**Pull request merged**
